ckanext/publikasi/views.py
from flask import (Blueprint, render_template, jsonify, request, url_for)
from ckan.lib.helpers import Page, pager_url
import ckan.plugins.toolkit as tk

PUBLIKASI_TYPE = ['publikasi sektoral', 'produk hukum']

bp = Blueprint(
    "publikasi",
    __name__,
    url_prefix="/publikasi"
)


def index():
    # dummy_publikasi = [
    #     {'id': 123, 'title': 'contoh publikasi', 'description': 'deskripsi publikasi 001', 'created': 'tgl 5'}, 
    #     {'id': 234, 'title': 'contoh publikasi 02', 'description': 'deskripsi publikasi 002', 'created': 'tgl 5'} 
    # ]

    # if t not in PUBLIKASI_TYPE:
    #     return {'status': 'Not Found'}, 404
    page_no = request.args.get('page', 1, type=int)
    sortby = request.args.get('sort', 'meta_release_date desc', type=str)
    query = request.args.get('q', '', type=str)

    ITEMS_PER_PAGE = 8
    # per_page = request.args.get('per_page', 10, type=int)
    print(f"anda sekarang berada di halaman : {page_no}")

    # data_publikasi = tk.get_action('publikasi_sektoral_get_all')(context={}, data_dict={})
    data_publikasi = tk.get_action('publikasi_sektoral_page')(context={}, \
        data_dict={'page_no': page_no, 'items_per_page': ITEMS_PER_PAGE, 'sortby': sortby, 'query': query})
    page = Page(
        collection=data_publikasi['items'],
        page=page_no,
        url=pager_url,
        item_count=data_publikasi['item_count'],
        items_per_page=ITEMS_PER_PAGE,
    )
    return render_template('publikasi/index.html', response={'data': data_publikasi['items'], 'page': page}, q=query, sort_by_selected=sortby)

def create():
    # if t not in PUBLIKASI_TYPE: 
    #     return 404
    return render_template('publikasi/publikasi_form.html')

def store():
    data_form = request.form
    print(data_form)

    data_publikasi = {
        'title': data_form.get('title'),
        'description': data_form.get('description'),
        'author': data_form.get('author'),
        'type' : data_form.get('type'),
        # 'cover_image': data_form.get('cover_image'),
        'cover_image': request.files['cover_image'],
        'publication_file': request.files['publication_file'],
        'catalog_number': data_form.get('catalog_number'),
        'publication_number': data_form.get('publication_number'),
        'isbn_issn': data_form.get('isbn_issn'),
        'release_frequency': data_form.get('release_frequency'),
        'release_date': data_form.get('release_date'),
        'language': data_form.get('language'),
    }

    publikasi_instance = tk.get_action('publikasi_create')(context={}, data_dict=data_publikasi)
    print('publikasi instance : {}'.format(publikasi_instance))

    # return jsonify({'data': publikasi_instance['publikasi']})

    return tk.redirect_to('publikasi.index')

def get(id):
    
    publikasi = tk.get_action('publikasi_get')(context={}, data_dict={'id': id})

    return render_template('publikasi/publikasi_read.html', response={'data': publikasi})

def edit(id):
    publikasi = tk.get_action('publikasi_get')(context={}, data_dict={'id': id})

    return render_template('publikasi/publikasi_form.html', mode='edit', response={'data': publikasi})

def update(id):
    data_form = request.form
    print(data_form)

    data_publikasi = {
        'id': id,
        'title': data_form.get('title'),
        'description': data_form.get('description'),
        'author': data_form.get('author'),
        'type' : data_form.get('type'),
        # 'cover_image': data_form.get('cover_image'),
        'cover_image': request.files['cover_image'],
        'publication_file': request.files['publication_file'],
        'catalog_number': data_form.get('catalog_number'),
        'publication_number': data_form.get('publication_number'),
        'isbn_issn': data_form.get('isbn_issn'),
        'release_frequency': data_form.get('release_frequency'),
        'release_date': data_form.get('release_date'),
        'language': data_form.get('language'),
    }

    publikasi_instance = tk.get_action('publikasi_update')(context={}, data_dict=data_publikasi)
    print('publikasi instance : {}'.format(publikasi_instance))

    # return jsonify({'data': publikasi_instance['publikasi']})

    return tk.redirect_to('publikasi.get', id=id)


def delete(id):

    tk.get_action('publikasi_delete')(context={}, data_dict={'id': id})

    return tk.redirect_to('publikasi.index')


bp.add_url_rule(
    '/', endpoint='index', view_func=index
)
bp.add_url_rule(
    '/add', endpoint='create', view_func=create, methods=['GET']
)
bp.add_url_rule(
    '/add', endpoint='store', view_func=store, methods=['POST']
)
bp.add_url_rule(
    '/<int:id>', endpoint='get', view_func=get
)
bp.add_url_rule(
    '/edit/<int:id>', endpoint='edit', view_func=edit
)
bp.add_url_rule(
    '/update/<int:id>', endpoint='update', view_func=update, methods=['POST']
)
bp.add_url_rule(
    '/delete/<int:id>', endpoint='delete', view_func=delete, methods=['POST']
)

def get_blueprints():
    return [bp]

ckanext/publikasi/templates/base.html
{% ckan_extends %}

{% block styles %}
    {{ super() }}
    {% asset 'publikasi/publikasi-preview-image-css' %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% asset 'publikasi/publikasi-preview-image' %}
{% endblock %}

ckanext/publikasi/templates/header.html
{% ckan_extends %}

{% block header_site_navigation_tabs %}
    {{ super() }}
    <li role="presentation" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Publikasi <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ url_for('publikasi.index' )}}">Publikasi Sektoral</a></li>
            <li><a href="{{ url_for('produk_hukum.index') }}">Produk Hukum</a></li>
        </ul>
    </li>      
{% endblock %}

ckanext/publikasi/templates/produk_hukum/index.html
{% extends 'page.html' %}

{% block subtitle %}Produk Hukum{% endblock %}

{% block breadcrumb_content %}
    <li>{% link_for _('Produk Hukum'), named_route='produk_hukum.index' %}</li>
{% endblock %}

{% block page_header %}{% endblock %}

{% block page_primary_action %}
    {% if h.check_access('publikasi_create') %}
        {% link_for _('Tambah Produk Hukum'), named_route='produk_hukum'+'.create', class_='btn btn-primary', icon='plus-square' %}
    {% endif %}
{% endblock %}

{% block primary_content_inner %}
    
    {% set sorting = [
        (_('Terbaru ke Paling Lama'), 'meta_release_date desc'),
        (_('Paling Lama ke Terbaru'), 'meta_release_date asc'),
        (_('A-Z (menaik)'), 'title asc'),
        (_('Z-A (menurun)'), 'title desc') ]
    %}
    {% snippet 'snippets/search_form.html', type='Publication', query=q, sorting_selected=sort_by_selected, placeholder='Cari Produk Hukum', count=response['page'].item_count, sorting=sorting %}

    {% if response['data'] %}
        {{ h.snippet('produk_hukum/snippets/produk_hukum_list.html', data=response['data']) }}
    {% else %}
        <p><i>Belum ada dokumen Produk Hukum</i></p>
    {% endif %}

    {% block page_pagination %}
        {{ response['page'].pager(q=q) }}
    {% endblock %}

{% endblock %}

{% block secondary_content %}
    {% snippet 'produk_hukum/snippets/helper.html' %}
{% endblock %}

ckanext/publikasi/templates/produk_hukum/produk_hukum_form.html
{% import 'macros/form.html' as Form %}
{% extends 'page.html' %}


{% set mode = mode or 'create' %}

{% if response %}
    {% set publikasi = response['data'] %}
{% else %}
    {% set publikasi = {} %}
{% endif %}

{% if mode == 'edit' %}
    {% set url_action %}
        {{ url_for('produk_hukum.update', id=publikasi.id) }}
    {% endset %}
{% else %}
    {% set url_action %}
        {{ url_for('produk_hukum.store') }}
    {% endset %}
{% endif %}


{% block breadcrumb_content %}
    {{ super() }}
    <li>{% link_for _('Produk Hukum'), named_route='produk_hukum.index' %}</li>
    <li class="active"><a href="">Form Produk Hukum</a></li>
{% endblock %}

{% block content_action %}
    {% if mode=='edit' %}
        {% link_for _('View'), named_route='produk_hukum.get', id=publikasi.id, class_='btn btn-default', icon='eye' %}
    {% endif %}
{% endblock %}

{% block content_primary_nav %}
    {% if mode=='edit' %}
        {{ h.build_nav_icon('produk_hukum.edit', _('Edit Produk Hukum'), id=publikasi.id, icon='') }}
    {% else %}
        {{ h.build_nav_icon('produk_hukum.create', _('Form Produk Hukum'), icon='plus') }}
    {% endif %}
{% endblock %}

{% block primary_content_inner %}
    
mode : {{ mode|pprint }}
    <!-- <form action="{{ url_for('publikasi.store')}}" method="post" class="form" enctype="multipart/form-data"> -->
    <form action="{{ url_action }}" method="post" class="form" enctype="multipart/form-data">
        {{ Form.input('title', label="Title", placeholder='title...', is_required=true, value=publikasi.title)}}

        {{ Form.markdown('description', label="Deskripsi", placeholder="description ...", value=publikasi.description)}}

        {{ Form.input('author', label='Author', value=publikasi.author) }}

        <input type="hidden" name="type" value="Produk Hukum">

        <div class="row">
            <div class="col-md-5">

                {% block upload_file_field %}
                {% set base_path = 'uploads/' %}
                {% set current_file %}
                    {% if publikasi %}
                        current_file = base_path + publikasi.file_path
                    {% else %}
                        current_file = ''
                    {% endif %}
                {% endset %}
                <!-- <p>upload file here</p> -->
                <div class="form-group">
                    <label for="">Upload berkas publikasi</label>
                    <input type="file" name="publication_file" id="field_publication_file" class="form-control" value="{{ current_file }}" required>
                </div>
                {% endblock %}

                {% block field_upload_cover %}
                    <!-- <div class="mt-5">
                        <h1 class="text-center mb-4">Upload Cover Image</h1>
                        <div class="text-center">
                            <div class="upload-container">
                                <img src="" alt="Image Preview">
                                <div class="upload-button">Click to Upload</div>
                                <input type="file" id="imageInput" class="form-control" style="opacity: 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer;">
                            </div>
                        </div>
                    </div> -->

                    <div class="cover-container mt-5">
                        <!-- <picture width="100%" height="400px"> -->
                        {%- set cover_img_src -%}
                            {% if publikasi.cover_image %}
                                {{- '/uploads/'+ publikasi.cover_image -}}
                            {% else %}
                                {{- '/images/placeholder_publikasi_file.jpg' -}}
                            {% endif %}
                        {%- endset -%}
                        <!-- </picture> -->
                        <h3 class="text-center mb-4">Cover Image</h3>
                        <div class="text-center">
                            <div class="upload-container">
                                <img id="imgPreviewContainer" src="{{ cover_img_src }}" alt="Image Preview">
                                <div class="upload-button">Click to Upload</div>
                                <input type="file" class="form-control"  name="cover_image"
                                    id="field_cover_image" data-module="preview_image" value="{{ publikasi.cover_image }}"
                                    accept=".jpg, .jpeg, .png, .svg"
                                    style="opacity: 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer;">
                            </div>
                        </div>
                    </div>
                    
                {% endblock %}
            </div>
            <div class="col-md-7">
                {{ Form.input('catalog_number', label="Nomor Katalog", value=publikasi.meta_catalog_number) }}

                {{ Form.input('publication_number', label='Nomor Publikasi', value=publikasi.meta_publication_number) }}

                {{ Form.input('isbn_issn', label='ISBN / ISSN', value=publikasi.meta_isbn_issn) }}

                {{ Form.input('release_frequency', label='Frekuensi Rilis', value=publikasi.meta_release_frequency)}}

                {# 
                {{ Form.input('release_date', label='Tanggal Rilis') }}
                #}
                
                <div class="form-group">
                    <label for="">Tanggal Rilis</label>
                    <input type="date" name="release_date" id="field_release_date" value="{% if publikasi.meta_release_date %}{{ h.datetime_field_format(publikasi.meta_release_date) }}{% endif %}" class="form-control">
                </div>

                {{ Form.input('language', label='Bahasa', value=publikasi.meta_language)}}

            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary pull-right" value="submit">{{ _('Save') }}</button>

                {#
                <button type="submit" form="form_delete" class="btn btn-danger pull-left" data-module="confirm-form" data-module-content="{{ _('Are you sure?')}}">Delete</button>
                #}
                 {% if mode=='edit' %}
                    <a href="{{ url_for('produk_hukum.delete', id=publikasi.id)}}" class="btn btn-danger pull-left" data-module="confirm-action" data-module-content="{{ _('Are you sure?')}}">Delete</a>
                 {% endif %}
            </div>
        </div>

    </form>


{% endblock %}

ckanext/publikasi/templates/produk_hukum/produk_hukum_read.html
{% extends 'page.html' %}

{% set data = response.data %}

{% block page_primary_action %}
{% endblock %}

{% block breadcrumb_content %}
    {{ super() }}
    <li>{% link_for _('Produk Hukum'), named_route='produk_hukum.index' %}</li>
    <li class="active"><a href="">{{ h.resource_display_name(data) }}</a></li>
{% endblock %}

{% block content_action %}
    {% if h.check_access('publikasi_create') %}
        {% link_for _('Manage'), named_route='produk_hukum.edit', id=data.id, class_='btn btn-default', icon='wrench' %}
    {% endif %}
{% endblock %}
{% block content_primary_nav %}
  {{ h.build_nav_icon('produk_hukum.get', _('Produk Hukum'), id=data.id, icon='') }}
{% endblock %}
<!-- <div>
    <a href="{{ url_for('metadata.edit', id=data.id)}}" class="btn btn-default">
        <span class="glyphicon glyphicon-wrench"></span> Manage
    </a> 
</div> -->

{% block primary_content_inner %}

<h2 class="">{{ data.title }}</h2>

<div class="row">
    <div class="col-md-4">
        <div class="cover-container">
            <!-- <picture width="100%" height="400px"> -->
                {%- set cover_img_src -%}
                    {% if data.cover_image %}
                        {{- '/uploads/'+data.cover_image -}}
                    {% else %}
                        {{- '/images/placeholder_publikasi_file.jpg' -}}
                    {% endif %}
                {%- endset -%}
                <img src="{{ cover_img_src }}" alt="" width="100%" style="object-fit: cover; aspect-ratio: 2 / 3" class="img-rounded">
            <!-- </picture> -->
        </div>
        <div>&nbsp;</div>

        <a href="{% url_for_static('/uploads/' + data.file_path) %}" target="_blank" class="btn btn-lg btn-info btn-block">Unduh Publikasi</a>
    </div>
    <div class="col-md-8">
        <p><b>Abstraksi</b></p>
        <p>{{ h.markdown_extract(data.description, extract_length=0) }}</p>
        <table class="table table-condensed">
            <tr>
                <th width="30%">Nomor Katalog</th>
                <td width="5%">:</td>
                <td width="50%">{{ data.meta_catalog_number }}</td>
            </tr>
            <tr>
                <th>Nomor Publikasi</th>
                <td>:</td>
                <td>{{ data.meta_publication_number }}</td>
            </tr>
            <tr>
                <th>ISBN/ISSN</th>
                <td>:</td>
                <td>{{ data.meta_isbn_issn }}</td>
            </tr>
            <tr>
                <th>Frekuensi Terbit</th>
                <td>:</td>
                <td>{{ data.meta_release_frequency }}</td>
            </tr>
            <tr>
                <th>Tanggal Rilis</th>
                <td>:</td>
                <td>{{ h.string_datetime(data.meta_release_date) }}</td>
            </tr>
            <tr>
                <th>Bahasa</th>
                <td>:</td>
                <td>{{ data.meta_language }}</td>
            </tr>
            <tr>
                <th>Ukuran File</th>
                <td>:</td>
                <td>{{ h.display_size_in_mb(data.meta_file_size) }}</td>
            </tr>
        </table>
    </div>
</div>



{#
<div class="well">
    <strong>
        Download <span class="glyphicon glyphicon-save-file"></span>
    </strong>
    <a href="{% url_for_static('/uploads/' + data.file_path) %}">{{ data.file_path }}</a>
</div>

<div>
    <h3>Preview</h3>
    <object data="{{ '/uploads/'+ data.file_path }}" frameborder="0" width="100%" height="800"></object>
</div>

#}
    
{% endblock %}

ckanext/publikasi/templates/produk_hukum/snippets/helper.html
<div class="module module-narrow module-shallow">
  <h2 class="module-heading">
    <i class="fa fa-info-circle"></i>
    {{ _('What are Produk Hukum?') }}
  </h2>
  <div class="module-content">
    <p>
      {% trans %}
        <b>Produk Hukum</b> 
      {% endtrans %}
    </p>
  </div>
</div>

ckanext/publikasi/templates/produk_hukum/snippets/produk_hukum_list.html
{# 

Display a grid of publikasi items.

data - A list of publikasi.

Example:

    {% snippet "publikasi/snippets/publikasi_list.html" %}

#}
{% block publikasi_list %}
<div class="{{ list_class or 'dataset-list list-unstyled' }}">
    {% block publikasi_list_inner %}
        {% for publikasi in data %}
        <div class="panel panel-default">
            <div class="panel-body">
                
                <div class="media">
                    <div class="media-left">
                        {%- set cover_img_src -%}
                            {% if publikasi.cover_image %}
                                {{- '/uploads/'+ publikasi.cover_image -}}
                            {% else %}
                                {{- '/images/placeholder_publikasi_file.jpg' -}}
                            {% endif %}
                        {%- endset -%}
                        <a href="#">
                            <!-- <img class="media-object" src="https://placehold.co/80x80/png" alt="..."> -->
                            <img class="media-object img-rounded" src="{{ cover_img_src }}" alt="..." height="100" width="100" style="object-fit: contain;">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="{{ url_for('produk_hukum.get', id=publikasi.id) }}">
                            {{ publikasi.title}}
                            </a>
                        </h4>
                        <p>{{ h.markdown_extract(publikasi.description | truncate(150)) }}</p>
                        <small>
                            <span class="glyphicon glyphicon-calendar"></span> {{ h.string_datetime(publikasi.meta_release_date) }}
                        </small>
                    </div>
                </div> 
            </div>
        </div>
        {% endfor %}
    {% endblock %}
</div>
    
{% endblock %}

{% block add_scripts %}

  <script>
    console.log('test 123')
    
  </script>
  
{% endblock %}

ckanext/publikasi/templates/publikasi/index.html
{% extends 'page.html' %}

{% block subtitle %}Publikasi{% endblock %}

{% block breadcrumb_content %}
    {{ super() }}
    <li>{% link_for _('Publikasi'), named_route='publikasi.index' %}</li>
{% endblock %}

{% block page_header %}{% endblock %}

{% block page_primary_action %}
    {% if h.check_access('publikasi_create') %}
        {% link_for _('Add Publikasi'), named_route='publikasi'+'.create', class_='btn btn-primary', icon='plus-square' %}
    {% endif %}
{% endblock %}

{% block primary_content_inner %}
    
    {% set sorting = [
        (_('Terbaru ke Paling Lama'), 'meta_release_date desc'),
        (_('Paling Lama ke Terbaru'), 'meta_release_date asc'),
        (_('A-Z (menaik)'), 'title asc'),
        (_('Z-A (menurun)'), 'title desc') ]
    %}
    {% snippet 'snippets/search_form.html', type='Publication', query=q, sorting_selected=sort_by_selected, placeholder='Cari Publikasi', count=response['page'].item_count, sorting=sorting %}

    {% if response['data'] %}
        {{ h.snippet('publikasi/snippets/publikasi_list.html', data=response['data']) }}
    {% else %}
        <p><i>Belum ada dokumen publikasi</i></p>
    {% endif %}

    {% block page_pagination %}
        {{ response['page'].pager(q=q) }}
    {% endblock %}

{% endblock %}

{% block secondary_content %}
    {% snippet 'publikasi/snippets/helper.html' %}
{% endblock %}

ckanext/publikasi/templates/publikasi/publikasi_form.html
{% import 'macros/form.html' as Form %}
{% extends 'page.html' %}


{% set mode = mode or 'create' %}

{% if response %}
    {% set publikasi = response['data'] %}
{% else %}
    {% set publikasi = {} %}
{% endif %}

{% if mode == 'edit' %}
    {% set url_action %}
        {{ url_for('publikasi.update', id=publikasi.id) }}
    {% endset %}
{% else %}
    {% set url_action %}
        {{ url_for('publikasi.store') }}
    {% endset %}
{% endif %}


{% block breadcrumb_content %}
    {{ super() }}
    <li>{% link_for _('Publikasi'), named_route='publikasi.index' %}</li>
    <li class="active"><a href="">Form Publikasi</a></li>
{% endblock %}

{% block content_action %}
    {% if mode=='edit' %}
        {% link_for _('View'), named_route='publikasi.get', id=publikasi.id, class_='btn btn-default', icon='eye' %}
    {% endif %}
{% endblock %}

{% block content_primary_nav %}
    {% if mode=='edit' %}
        {{ h.build_nav_icon('publikasi.edit', _('Edit Publikasi'), id=publikasi.id, icon='') }}
    {% else %}
        {{ h.build_nav_icon('publikasi.create', _('Form Publikasi'), icon='plus') }}
    {% endif %}
{% endblock %}

{% block primary_content_inner %}
    
mode : {{ mode|pprint }}
    <!-- <form action="{{ url_for('publikasi.store')}}" method="post" class="form" enctype="multipart/form-data"> -->
    <form action="{{ url_action }}" method="post" class="form" enctype="multipart/form-data">
        {{ Form.input('title', label="Title", placeholder='title...', is_required=true, value=publikasi.title)}}

        {{ Form.markdown('description', label="Deskripsi", placeholder="description ...", value=publikasi.description)}}

        {{ Form.input('author', label='Author', value=publikasi.author) }}

        <input type="hidden" name="type" value="Publikasi Sektoral">

        <div class="row">
            <div class="col-md-5">

                {% block upload_file_field %}
                {% set base_path = 'uploads/' %}
                {% set current_file %}
                    {% if publikasi %}
                        current_file = base_path + publikasi.file_path
                    {% else %}
                        current_file = ''
                    {% endif %}
                {% endset %}
                <!-- <p>upload file here</p> -->
                <div class="form-group">
                    <label for="">Upload berkas publikasi</label>
                    <input type="file" name="publication_file" id="field_publication_file" class="form-control" value="{{ current_file }}" required>
                </div>
                {% endblock %}

                {% block field_upload_cover %}
                    <!-- <div class="mt-5">
                        <h1 class="text-center mb-4">Upload Cover Image</h1>
                        <div class="text-center">
                            <div class="upload-container">
                                <img src="" alt="Image Preview">
                                <div class="upload-button">Click to Upload</div>
                                <input type="file" id="imageInput" class="form-control" style="opacity: 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer;">
                            </div>
                        </div>
                    </div> -->

                    <div class="cover-container mt-5">
                        <!-- <picture width="100%" height="400px"> -->
                        {%- set cover_img_src -%}
                            {% if publikasi.cover_image %}
                                {{- '/uploads/'+ publikasi.cover_image -}}
                            {% else %}
                                {{- '/images/placeholder_publikasi_file.jpg' -}}
                            {% endif %}
                        {%- endset -%}
                        <!-- </picture> -->
                        <h3 class="text-center mb-4">Cover Image</h3>
                        <div class="text-center">
                            <div class="upload-container">
                                <img id="imgPreviewContainer" src="{{ cover_img_src }}" alt="Image Preview">
                                <div class="upload-button">Click to Upload</div>
                                <input type="file" class="form-control"  name="cover_image"
                                    id="field_cover_image" data-module="preview_image" value="{{ publikasi.cover_image }}"
                                    accept=".jpg, .jpeg, .png, .svg"
                                    style="opacity: 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: pointer;">
                            </div>
                        </div>
                    </div>
                    
                {% endblock %}
            </div>
            <div class="col-md-7">
                {{ Form.input('catalog_number', label="Nomor Katalog", value=publikasi.meta_catalog_number) }}

                {{ Form.input('publication_number', label='Nomor Publikasi', value=publikasi.meta_publication_number) }}

                {{ Form.input('isbn_issn', label='ISBN / ISSN', value=publikasi.meta_isbn_issn) }}

                {{ Form.input('release_frequency', label='Frekuensi Rilis', value=publikasi.meta_release_frequency)}}

                {# 
                {{ Form.input('release_date', label='Tanggal Rilis') }}
                #}
                
                <div class="form-group">
                    <label for="">Tanggal Rilis</label>
                    <input type="date" name="release_date" id="field_release_date" value="{% if publikasi.meta_release_date %}{{ h.datetime_field_format(publikasi.meta_release_date) }}{% endif %}" class="form-control">
                </div>

                {{ Form.input('language', label='Bahasa', value=publikasi.meta_language)}}

            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary pull-right" value="submit">{{ _('Save') }}</button>

                {#
                <button type="submit" form="form_delete" class="btn btn-danger pull-left" data-module="confirm-form" data-module-content="{{ _('Are you sure?')}}">Delete</button>
                #}
                 {% if mode=='edit' %}
                    <a href="{{ url_for('publikasi.delete', id=publikasi.id)}}" class="btn btn-danger pull-left" data-module="confirm-action" data-module-content="{{ _('Are you sure?')}}">Delete</a>
                 {% endif %}
            </div>
        </div>

    </form>


{% endblock %}

ckanext/publikasi/templates/publikasi/snippets/helper.html
<div class="module module-narrow module-shallow">
  <h2 class="module-heading">
    <i class="fa fa-info-circle"></i>
    {{ _('What are Publikasi?') }}
  </h2>
  <div class="module-content">
    <p>
      {% trans %}
        <b>Publikasi</b> 
      {% endtrans %}
    </p>
  </div>
</div>